### ISSUE TITLE
Mounting subdir of FS now possible(?)

### ISSUE THREAD

**Issue by Winterhuman** [uapi-group/kernel-features#16]
The docs for `man mount` mention `X-mount.subdir=/dir` being an existing, though experimental, option that can be used, which might satisfy the second entry in the readme (although it seems to use a similar "namespace exercise" to achieve this judging by the description, so maybe not).

If it isn't a clean solution, it might be worth mentioning in the readme what it doesn't do cleanly enough to be fully useful.

**Comment by poettering** [comment]
yeah, the mount namespacing shenanigans have been possible for a longer time (and systemd-homed even uses that!). But the feature request is really about doing that without that.

I clarified this now in #22.
